name: Restart Server

'on':
  workflow_dispatch:
    types:
      - restart

jobs:
  build:
    name: Restart
    runs-on: ubuntu-latest
    steps:
      - name: update docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_KEY }}
          port: ${{ vars.SERVER_PORT }}
          script: |
            cd ~/var/docker/
            docker-compose restart
